






// DIGITAL_CLOCK.v

module DIGITAL_CLOCK(
	RESETN, CLK,
	KEY,
   LCD_E, LCD_RS, LCD_RW,
	LCD_DATA, PIEZO
);

input RESETN, CLK;
input [4:0] KEY;
output wire LCD_E, LCD_RS, LCD_RW, PIEZO;
output wire [7:0] LCD_DATA;

wire [16:0] ALARM_TIME;
wire [17:0] CURRENT_TIME, CURRENT_DATE;

wire [16:0] SETTING_ALARM_TIME;
wire [17:0] SETTING_CURRENT_TIME, SETTING_CURRENT_DATE;

wire [5:0] MODE;
wire ALARM_ENABLE, SETTING;

// Key Controller
KEY_CONT(
	RESETN, CLK,
	KEY, CURRENT_TIME, CURRENT_DATE, ALARM_TIME,
	MODE, ALARM_ENABLE, SETTING,
	SETTING_CURRENT_TIME, SETTING_CURRENT_DATE, SETTING_ALARM_TIME
);

/// Time Calculator
TIME_CAL(
	RESETN, CLK,
	SETTING_CURRENT_TIME, SETTING_CURRENT_DATE, SETTING_ALARM_TIME,
	MODE[0], MODE[5], SETTING,
	CURRENT_TIME, CURRENT_DATE, ALARM_TIME
);

/// (current time) and (alarm time) compare
TIME_COMPARE(
	RESETN, CLK,
	ALARM_ENABLE, CURRENT_TIME[16:0], ALARM_TIME,
	ALARM_DOING
);

/// PIEZO
PIEZO_UNIT(
	RESETN, CLK,
	ALARM_DOING,
	PIEZO
);

/// LCD Controller
LCD_CONT(
    RESETN, CLK,
	 DISPLAY_TIME, DISPLAY_DATE,
	 MODE, CONT, RING_ALARM, SET_ALARM,
    LCD_E, LCD_RS, LCD_RW,
    LCD_DATA
);


endmodule
